### PR TITLE
start favorite_food_joints.txt

### PR DESCRIPTION
**Pull request by yoonboyeong**
Starting to work on #3

### CODE REVIEW

**Comment by yoonboyeong** [comment]
@vioelsdm Please review my work.

**Comment by Aleks118** [comment]
looks good. I would merge but I don't have write access

**Review by Aleks118 — APPROVED** [review]

**Review by Aleks118 — APPROVED** [review]

**Comment by yoonboyeong** [comment]
@Aleks118 @vioelsdm What's your favorite foods?

**Comment by Aleks118** [comment]
you can put -  "qdoba" and "any gyro place"

**Comment by suryacosm** [comment]
Yes, that's right! Merged after looking at the edits.

**Pull request merged**
