### PR TITLE
edit programming_languages.txt

### PR DESCRIPTION
**Pull request by yoonboyeong**
Starting to work on #10 

I am going to 
... 1. edit Nancy's programming language to JavaScript, not Java
... 2. add a table

### CODE REVIEW

**Comment by Aleks118** [comment]
I just saw the issue. I changed it on my local. I was about to start a pull request. But saw you already got it done

**Comment by yoonboyeong** [comment]
@Aleks118 Would you merge this?

**Comment by Aleks118** [comment]
I dont have write access

**Comment by Aleks118** [comment]
Screen Shot 2019-10-01 at 10 48 36 PM

**Review by Aleks118 — APPROVED** [review]

**Comment by nancydocode** [comment]
Oh, okay. I was there when Rio assigned us as contributors. Interesting. Sorry to ask you the same question.

**Comment by Aleks118** [comment]
Yeah i was there as well. I don't know

**Comment by suryacosm** [comment]
Ah sorry, that's me that has write access, I saw the edits and I think they are good and will merge.

**Pull request merged**
